### ISSUE TITLE
Patch to fix FTBFS issue for maya available

### ISSUE THREAD

**Issue by Conan-Kudo** [decathorpe/elementary-rpms#1]
A patch has been submitted on the issue that fixes the FTBFS condition you've been experiencing. It is available from this [Launchpad issue](https://bugs.launchpad.net/maya/+bug/1496653).

**Comment by decathorpe** [comment]
Sorry for the late reply - I completely forgot to update the maya packaging.
It is included in my copr repository now and added as of commit https://github.com/decathorpe/elementary-rpms/commit/73a3f63a4380088741981a67e1ccd3c09ae01fcc.
