### ISSUE TITLE
sqlheavy is not dead

### ISSUE THREAD

**Issue by Conan-Kudo** [decathorpe/elementary-rpms#2]
The sqlheavy library is not dead, and appears to be actively developed by its author [on GitHub](https://github.com/nemequ/sqlheavy/).

Footnote should be able to build against this library.

**Comment by decathorpe** [comment]
Last I checked, footnote depended on sqlheavy-1.0, which did not build with modern vala. I'll check on that later.

**Comment by decathorpe** [comment]
Yep, footnote still requires sqlheavy-1.0, which does not build with recent vala versions.
Also, 2-3 bugfix commits since 2012 and no commits since 5 months ago hardly qualify as "active development".
