### ISSUE TITLE
Request: 32 bit builds needed

### ISSUE THREAD

**Issue by sergioad** [decathorpe/elementary-rpms#3]
Hello friend could you build the same packages you build for 64 bit machines but for 32 bit ones? I know that there are not many 32 bit PCs out there but fedora keeps supporting them and honestly I want to get Vocal on my PC :smile: if you can build it on 32 bit I will thank you

**Comment by decathorpe** [comment]
Which Version of fedora are you using? I'd rather have build time increase by 1.5x than 2x :)

**Comment by sergioad** [comment]
@decathorpe Fc23

**Comment by decathorpe** [comment]
I will add 23-i386 to the next batch of updates.

**Comment by sergioad** [comment]
thank you very much :smile:
